# Bundesliga & Premier League -Transferanalyse 2026

## Ziel
Analyse der Transferaktivitäten der Bundesliga- und Premier League-Vereine mit Fokus auf
Ablösesummen, Marktwerte und Transferbilanzen.

## 1. Datenimport und erste Prüfung

In [1]:
import pandas as pd

bundesliga = pd.read_csv("Transfermarkt 2026.csv", sep=";")
premier_league = pd.read_csv("Transfermarkt 2026 Premier League.csv", sep=";")

In [2]:
bundesliga.head()

,Spieler,Alter,Nationalität,Position,Marktwert,Abgebender Verein,Aufnehmender Verein,Ablöse
0,Ismael Saibari,25,Marokko,Offensives Mittelfeld,"40,00 Mio. €",PSV Eindhoven,FC Bayern München,"50,00 Mio. €"
1,Nathaniel Brown,23,Deutschland,Linker Verteidiger,"40,00 Mio. €",Eintracht Frankfurt,FC Bayern München,"50,00 Mio. €"
2,Bara Sapoko Ndiaye,18,Senegal,Zentrales Mittelfeld,"4,00 Mio. €",Gambinos Stars,FC Bayern München,"3,50 Mio. €"
3,Noël Aséko,20,Deutschland,Defensives Mittelfeld,"12,00 Mio. €",Hannover 96,FC Bayern München,"3,45 Mio. €"
4,Noël Aséko,20,Deutschland,Defensives Mittelfeld,"12,00 Mio. €",FC Bayern München,E. Frankfurt,"12,00 Mio. €"

In [3]:
premier_league.head()

,Spieler,Alter,Nationalität,Position,Marktwert,Abgebender Verein,Aufnehmender Verein,Ablöse
0,Bruno Guimarães,28,Brasilien,Zentrales Mittelfeld,"70,00 Mio. €",Newcastle United,FC Arsenal,"87,50 Mio. €"
1,Ezri Konsa,28,England,Innenverteidiger,"45,00 Mio. €",Aston Villa,FC Arsenal,"59,60 Mio. €"
2,Piero Hincapié,24,Ecuador,Innenverteidiger,"50,00 Mio. €",Bayer 04 Leverkusen,FC Arsenal,"40,00 Mio. €"
3,Christos Tzolis,24,Griechenland,Linksaußen,"40,00 Mio. €",Club Brügge,FC Arsenal,"40,00 Mio. €"
4,Illan Meslier,26,Frankreich,Torwart,"8,00 Mio. €",Leeds United,FC Arsenal,ablösefrei

In [4]:
bundesliga.info()

<class 'pandas.DataFrame'>
RangeIndex: 262 entries, 0 to 261
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Spieler              262 non-null    str
 1   Alter                262 non-null    int64
 2   Nationalität         262 non-null    str
 3   Position             262 non-null    str
 4   Marktwert            262 non-null    str
 5   Abgebender Verein    262 non-null    str
 6   Aufnehmender Verein  262 non-null    str
 7   Ablöse               262 non-null    str
dtypes: int64(1), str(7)
memory usage: 16.5 KB

In [5]:
premier_league.info()

<class 'pandas.DataFrame'>
RangeIndex: 249 entries, 0 to 248
Data columns (total 8 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Spieler              249 non-null    str
 1   Alter                249 non-null    int64
 2   Nationalität         249 non-null    str
 3   Position             249 non-null    str
 4   Marktwert            249 non-null    str
 5   Abgebender Verein    249 non-null    str
 6   Aufnehmender Verein  249 non-null    str
 7   Ablöse               249 non-null    str
dtypes: int64(1), str(7)
memory usage: 15.7 KB

In [6]:
bundesliga.isna().sum()

Spieler                0
Alter                  0
Nationalität           0
Position               0
Marktwert              0
Abgebender Verein      0
Aufnehmender Verein    0
Ablöse                 0
dtype: int64

In [7]:
premier_league.isna().sum()

Spieler                0
Alter                  0
Nationalität           0
Position               0
Marktwert              0
Abgebender Verein      0
Aufnehmender Verein    0
Ablöse                 0
dtype: int64

## 2. Datenqualität und Bereinigung

Überprüfung auf fehlende Werte, Duplikate und uneinheitliche Werteformate.

In [8]:
bundesliga.duplicated().sum()

np.int64(10)

In [9]:
premier_league.duplicated().sum()

np.int64(20)

In [10]:
bundesliga[bundesliga.duplicated(keep=False)].sort_values("Spieler")

,Spieler,Alter,Nationalität,Position,Marktwert,Abgebender Verein,Aufnehmender Verein,Ablöse
200,Eric Martel,24,Deutschland,Defensives Mittelfeld,"8,00 Mio. €",1.FC Köln,1.FSV Mainz 05,ablösefrei
130,Eric Martel,24,Deutschland,Defensives Mittelfeld,"8,00 Mio. €",1.FC Köln,1.FSV Mainz 05,ablösefrei
61,Hennes Behrens,21,Deutschland,Linker Verteidiger,"5,00 Mio. €",TSG 1899 Hoffenheim,FC Augsburg,"3,50 Mio. €"
110,Hennes Behrens,21,Deutschland,Linker Verteidiger,"5,00 Mio. €",TSG 1899 Hoffenheim,FC Augsburg,"3,50 Mio. €"
223,Junior Adamu,25,Österreich,Mittelstürmer,"3,00 Mio. €",SC Freiburg,FC Schalke 04,800 Tsd. €
91,Junior Adamu,25,Österreich,Mittelstürmer,"3,00 Mio. €",SC Freiburg,FC Schalke 04,800 Tsd. €
105,Junior Dina Ebimbe,25,Kamerun,Rechtes Mittelfeld,"6,00 Mio. €",Eintracht Frankfurt,FC Schalke 04,800 Tsd. €
224,Junior Dina Ebimbe,25,Kamerun,Rechtes Mittelfeld,"6,00 Mio. €",Eintracht Frankfurt,FC Schalke 04,800 Tsd. €
62,Luca Erlein,19,Deutschland,Rechter Verteidiger,"2,00 Mio. €",TSG 1899 Hoffenheim,Bayer 04 Leverkusen,"2,00 Mio. €"
74,Luca Erlein,19,Deutschland,Rechter Verteidiger,"2,00 Mio. €",TSG 1899 Hoffenheim,Bayer 04 Leverkusen,"2,00 Mio. €"
248,Luka Duric,23,Bosnien-Herzegowina,Zentrales Mittelfeld,800 Tsd. €,TSG 1899 Hoffenheim,SC Paderborn 07,250 Tsd. €
64,Luka Duric,23,Bosnien-Herzegowina,Zentrales Mittelfeld,800 Tsd. €,TSG 1899 Hoffenheim,SC Paderborn 07,250 Tsd. €
143,Marvin Friedrich,30,Deutschland,Innenverteidiger,"1,80 Mio. €",Borussia Mönchengladbach,1.FC Union Berlin,ablösefrei
174,Marvin Friedrich,30,Deutschland,Innenverteidiger,"1,80 Mio. €",Borussia Mönchengladbach,1.FC Union Berlin,ablösefrei
101,Nathaniel Brown,23,Deutschland,Linker Verteidiger,"40,00 Mio. €",Eintracht Frankfurt,FC Bayern München,"50,00 Mio. €"
1,Nathaniel Brown,23,Deutschland,Linker Verteidiger,"40,00 Mio. €",Eintracht Frankfurt,FC Bayern München,"50,00 Mio. €"
168,Rocco Reitz,24,Deutschland,Zentrales Mittelfeld,"20,00 Mio. €",Borussia Mönchengladbach,RB Leipzig,"20,00 Mio. €"
31,Rocco Reitz,24,Deutschland,Zentrales Mittelfeld,"20,00 Mio. €",Borussia Mönchengladbach,RB Leipzig,"20,00 Mio. €"
142,Stanley Nsoki,27,Frankreich,Innenverteidiger,"2,00 Mio. €",TSG 1899 Hoffenheim,1.FC Union Berlin,"1,50 Mio. €"
63,Stanley Nsoki,27,Frankreich,Innenverteidiger,"2,00 Mio. €",TSG 1899 Hoffenheim,1.FC Union Berlin,"1,50 Mio. €"

In [11]:
premier_league[premier_league.duplicated(keep=False)].sort_values("Spieler")

,Spieler,Alter,Nationalität,Position,Marktwert,Abgebender Verein,Aufnehmender Verein,Ablöse
236,Andrew Robertson,32,Schottland,Linker Verteidiger,"7,00 Mio. €",FC Liverpool,Tottenham Hotspur,ablösefrei
162,Andrew Robertson,32,Schottland,Linker Verteidiger,"7,00 Mio. €",FC Liverpool,Tottenham Hotspur,ablösefrei
67,Andrey Santos,22,Brasilien,Defensives Mittelfeld,"40,00 Mio. €",FC Chelsea,Manchester United,"56,30 Mio. €"
179,Andrey Santos,22,Brasilien,Defensives Mittelfeld,"40,00 Mio. €",FC Chelsea,Manchester United,"56,30 Mio. €"
92,Brennan Johnson,25,Wales,Rechtsaußen,"30,00 Mio. €",Crystal Palace,FC Everton,"25,80 Mio. €"
89,Brennan Johnson,25,Wales,Rechtsaußen,"30,00 Mio. €",Crystal Palace,FC Everton,"25,80 Mio. €"
48,Carl Rushworth,25,England,Torwart,"16,00 Mio. €",Brighton & Hove Albion,Coventry City,"25,70 Mio. €"
72,Carl Rushworth,25,England,Torwart,"16,00 Mio. €",Brighton & Hove Albion,Coventry City,"25,70 Mio. €"
96,Christian Nørgaard,32,Dänemark,Defensives Mittelfeld,"5,00 Mio. €",FC Arsenal,FC Everton,"8,15 Mio. €"
8,Christian Nørgaard,32,Dänemark,Defensives Mittelfeld,"5,00 Mio. €",FC Arsenal,FC Everton,"8,15 Mio. €"
50,Danny Welbeck,35,England,Mittelstürmer,"3,00 Mio. €",Brighton & Hove Albion,FC Chelsea,"5,85 Mio. €"
64,Danny Welbeck,35,England,Mittelstürmer,"3,00 Mio. €",Brighton & Hove Albion,FC Chelsea,"5,85 Mio. €"
83,Dwight McNeil,26,England,Linksaußen,"18,00 Mio. €",FC Everton,Crystal Palace,"25,80 Mio. €"
97,Dwight McNeil,26,England,Linksaußen,"18,00 Mio. €",FC Everton,Crystal Palace,"25,80 Mio. €"
213,Elliot Anderson,23,England,Zentrales Mittelfeld,"110,00 Mio. €",Nottingham Forest,Manchester City,"135,00 Mio. €"
166,Elliot Anderson,23,England,Zentrales Mittelfeld,"110,00 Mio. €",Nottingham Forest,Manchester City,"135,00 Mio. €"
37,Frank Onyeka,28,Nigeria,Zentrales Mittelfeld,"8,00 Mio. €",FC Brentford,Coventry City,"7,00 Mio. €"
77,Frank Onyeka,28,Nigeria,Zentrales Mittelfeld,"8,00 Mio. €",FC Brentford,Coventry City,"7,00 Mio. €"
158,Illan Meslier,26,Frankreich,Torwart,"8,00 Mio. €",Leeds United,FC Arsenal,ablösefrei
4,Illan Meslier,26,Frankreich,Torwart,"8,00 Mio. €",Leeds United,FC Arsenal,ablösefrei
149,James Trafford,23,England,Torwart,"25,00 Mio. €",Manchester City,Leeds United,"46,70 Mio. €"
174,James Trafford,23,England,Torwart,"25,00 Mio. €",Manchester City,Leeds United,"46,70 Mio. €"
235,Jan Paul van Hecke,26,Niederlande,Innenverteidiger,"45,00 Mio. €",Brighton & Hove Albion,Tottenham Hotspur,"60,00 Mio. €"
47,Jan Paul van Hecke,26,Niederlande,Innenverteidiger,"45,00 Mio. €",Brighton & Hove Albion,Tottenham Hotspur,"60,00 Mio. €"
115,Joe Gelhardt,24,England,Mittelstürmer,"14,00 Mio. €",Leeds United,Hull City,"7,60 Mio. €"
154,Joe Gelhardt,24,England,Mittelstürmer,"14,00 Mio. €",Leeds United,Hull City,"7,60 Mio. €"
39,Jordan Henderson,36,England,Zentrales Mittelfeld,"1,20 Mio. €",FC Brentford,FC Chelsea,ablösefrei
66,Jordan Henderson,36,England,Zentrales Mittelfeld,"1,20 Mio. €",FC Brentford,FC Chelsea,ablösefrei
181,Karl Darlow,35,Wales,Torwart,200 Tsd. €,Leeds United,Manchester United,ablösefrei
157,Karl Darlow,35,Wales,Torwart,200 Tsd. €,Leeds United,Manchester United,ablösefrei
240,Luka Vuskovic,19,Kroatien,Innenverteidiger,"60,00 Mio. €",Tottenham Hotspur,Brighton & Hove Albion,"54,00 Mio. €"
40,Luka Vuskovic,19,Kroatien,Innenverteidiger,"60,00 Mio. €",Tottenham Hotspur,Brighton & Hove Albion,"54,00 Mio. €"
57,Maxence Lacroix,26,Frankreich,Innenverteidiger,"50,00 Mio. €",Crystal Palace,FC Chelsea,"60,70 Mio. €"
88,Maxence Lacroix,26,Frankreich,Innenverteidiger,"50,00 Mio. €",Crystal Palace,FC Chelsea,"60,70 Mio. €"
153,Pascal Struijk,26,Niederlande,Innenverteidiger,"22,00 Mio. €",Leeds United,Brighton & Hove Albion,"23,20 Mio. €"
42,Pascal Struijk,26,Niederlande,Innenverteidiger,"22,00 Mio. €",Leeds United,Brighton & Hove Albion,"23,20 Mio. €"
214,Taiwo Awoniyi,29,Nigeria,Mittelstürmer,"8,00 Mio. €",Nottingham Forest,Coventry City,"10,50 Mio. €"
76,Taiwo Awoniyi,29,Nigeria,Mittelstürmer,"8,00 Mio. €",Nottingham Forest,Coventry City,"10,50 Mio. €"
70,Tyrique George,20,England,Linksaußen,"20,00 Mio. €",FC Chelsea,FC Everton,"21,00 Mio. €"
94,Tyrique George,20,England,Linksaußen,"20,00 Mio. €",FC Chelsea,FC Everton,"21,00 Mio. €"

In [12]:
bundesliga = bundesliga.drop_duplicates()

In [13]:
premier_league = premier_league.drop_duplicates()

### Bereinigung von Ablöse und Marktwert

Sonderwerte wie ablösefreie Transfers und unbekannte Ablösesummen werden
für die weitere Analyse vereinheitlicht.

In [14]:
bundesliga["Ablöse"].value_counts()

Ablöse
-               57
ablösefrei      57
3,50 Mio. €     10
?                9
500 Tsd. €       6
                ..
1,75 Mio. €      1
17,00 Mio. €     1
8,50 Mio. €      1
50 Tsd. €        1
5,25 Mio. €      1
Name: count, Length: 66, dtype: int64

In [15]:
bundesliga[bundesliga["Ablöse"].isin(["-", "?", "ablösefrei"])]

,Spieler,Alter,Nationalität,Position,Marktwert,Abgebender Verein,Aufnehmender Verein,Ablöse
12,Leon Goretzka,31,Deutschland,Zentrales Mittelfeld,"12,00 Mio. €",FC Bayern München,Vereinslos,-
13,Raphaël Guerreiro,32,Portugal,Linker Verteidiger,"5,00 Mio. €",FC Bayern München,Vereinslos,-
14,Tarek Buchmann,21,Deutschland,Innenverteidiger,300 Tsd. €,FC Bayern München,B. München II,-
20,Mussa Kaba,17,Deutschland,Defensives Mittelfeld,200 Tsd. €,Borussia Dortmund II,Borussia Dortmund,-
21,Samuele Inácio,18,Italien,Hängende Spitze,"15,00 Mio. €",Borussia Dortmund II,Borussia Dortmund,-
...,...,...,...,...,...,...,...,...
256,Lasse Eickel,18,Deutschland,Mittelstürmer,150 Tsd. €,SC Paderborn 07 II,SC Paderborn 07,-
258,David Kinsombi,30,Deutschland,Defensives Mittelfeld,400 Tsd. €,SC Paderborn 07,Deutschland Würzb. Kickers,ablösefrei
259,Calvin Brackelmann,26,Deutschland,Innenverteidiger,"3,00 Mio. €",SC Paderborn 07,Deutschland FC Augsburg,ablösefrei
260,Filip Bilbija,26,Deutschland,Linksaußen,"3,00 Mio. €",SC Paderborn 07,England Derby County,ablösefrei
261,Lucas Copado,22,Deutschland,Mittelstürmer,600 Tsd. €,SC Paderborn 07,Deutschland Energie Cottbus,?

In [16]:
bundesliga[bundesliga["Marktwert"] == "-"]

,Spieler,Alter,Nationalität,Position,Marktwert,Abgebender Verein,Aufnehmender Verein,Ablöse
28,Niklas Süle,30,Deutschland,Innenverteidiger,-,Borussia Dortmund,SV Tiefenbach,ablösefrei
45,Ertugrul Yigit,17,Deutschland,Zentrales Mittelfeld,-,VfB Stuttgart U19,VFB Stuttgart,-
75,Ndjicoura Bomba,18,Mali,Mittelstürmer,-,Club Sportif de Bamako,Bayer 04 Leverkusen,"1,50 Mio. €"
76,Naba Mensah,19,Deutschland,Zentrales Mittelfeld,-,Bayer 04 Leverkusen U19,Bayer 04 Leverkusen,-
99,Malik Pimpong,18,Dänemark,Linksaußen,-,FC Midtjylland U19,Eintracht Frankfurt,"3,50 Mio. €"
114,Tom Wisbereit,18,Deutschland,Torwart,-,1.FC Union Berlin U19,FC Augsburg,ablösefrei
145,Leon Prosche,19,Deutschland,Innenverteidiger,-,1.FC Union Berlin U19,1.FC Union Berlin,-
146,Mekhi Gray,19,Jamaika,Mittelstürmer,-,1.FC Union Berlin U19,1.FC Union Berlin,-
147,Tim Blaszczak,18,Deutschland,Defensives Mittelfeld,-,1.FC Union Berlin U19,1.FC Union Berlin,-
167,Mathieu Nguefack,18,Deutschland,Zentrales Mittelfeld,-,Borussia Mönchengladbach II,Borussia Mönchengladbach,-
180,Mads Bröcker,18,Deutschland,Offensives Mittelfeld,-,RB Leipzig U19,Hamburg SV,?
181,Mario Vuskovic,24,Kroatien,Innenverteidiger,-,Sperre,Hamburg SV,-
183,Finn Barkowsky,18,Deutschland,Linksaußen,-,Hamburger SV U19,Hamburg SV,-
193,Reigan Heskey,18,England,Linksaußen,-,Manchester City U21,1.FC Köln,"2,00 Mio. €"
195,Martin James,18,Frankreich,Torwart,-,Paris Saint-Germain Espoirs,1.FC Köln,ablösefrei
197,Gil Neves,18,Portugal,Offensives Mittelfeld,-,Benfica Lissabon U23,1.FC Köln,?
211,Darwin Soylu,19,Türkei,Offensives Mittelfeld,-,VfL Wolfsburg U19,SV Werder Bremen,ablösefrei
228,Luca Vozar,19,Deutschland,Defensives Mittelfeld,-,FC Schalke 04 U19,FC Schalke 04,-
240,Elias Etringer,18,Deutschland,Torwart,-,SC Freiburg U19,SV 07 Elversberg,ablösefrei

In [17]:
premier_league["Ablöse"].value_counts()

Ablöse
ablösefrei       43
-                31
40,00 Mio. €      8
25,00 Mio. €      7
7,00 Mio. €       6
                 ..
1,40 Mio. €       1
108,00 Mio. €     1
99,00 Mio. €      1
8,20 Mio. €       1
5,30 Mio. €       1
Name: count, Length: 98, dtype: int64

In [18]:
premier_league[premier_league["Ablöse"].isin(["-", "?", "ablösefrei"])]

,Spieler,Alter,Nationalität,Position,Marktwert,Abgebender Verein,Aufnehmender Verein,Ablöse
4,Illan Meslier,26,Frankreich,Torwart,"8,00 Mio. €",Leeds United,FC Arsenal,ablösefrei
5,Tommy Setford,20,England,Torwart,500 Tsd. €,FC Arsenal U21,FC Arsenal,-
15,George Hemmings,19,England,Zentrales Mittelfeld,800 Tsd. €,Aston Villa U21,FC Aston Villa,-
29,Marcos Senesi,29,Argentinien,Innenverteidiger,"25,00 Mio. €",AFC Bournemouth,England Tottenham,ablösefrei
30,Enes Ünal,29,Türkei,Mittelstürmer,"7,00 Mio. €",AFC Bournemouth,Spanien FC Getafe,ablösefrei
...,...,...,...,...,...,...,...,...
232,Niall Huggins,25,Wales,Rechter Verteidiger,600 Tsd. €,AFC Sunderland,Vereinslos,-
237,Marcos Senesi,29,Argentinien,Innenverteidiger,"25,00 Mio. €",AFC Bournemouth,Tottenham Hotspur,ablösefrei
238,Martin Dúbravka,37,Slowakei,Torwart,500 Tsd. €,FC Burnley,Tottenham Hotspur,ablösefrei
239,Will Lankshear,21,England,Mittelstürmer,"7,00 Mio. €",Tottenham Hotspur U21,Tottenham Hotspur,-
248,Yves Bissouma,29,Mali,Defensives Mittelfeld,"10,00 Mio. €",Tottenham Hotspur,Vereinslos,-

In [19]:
premier_league[premier_league["Marktwert"] == "-"]

,Spieler,Alter,Nationalität,Position,Marktwert,Abgebender Verein,Aufnehmender Verein,Ablöse
36,Josh Stephenson,20,England,Innenverteidiger,-,FC Brentford U21,FC Brentford,-
63,Denner,18,Brasilien,Linker Verteidiger,-,SC Corinthians U20,FC Chelsea,"10,00 Mio. €"
171,Ryan McAidoo,18,England,Rechtsaußen,-,Manchester City U21,Manchester City,-
184,Dermot Mee,23,Nordirland,Torwart,-,Manchester United U21,Manchester United,-
200,Leo Shahar,19,England,Rechter Verteidiger,-,Newcastle United U21,Newcastle United,-
208,Leo Shahar,19,England,Rechter Verteidiger,-,Newcastle United,Newcastle United U21,-

In [20]:
import numpy as np

bundesliga["Ablöse"] = bundesliga["Ablöse"].replace({
    "ablösefrei": "0",
    "?": np.nan,
    "-": np.nan
})

bundesliga["Marktwert"] = bundesliga["Marktwert"].replace("-", np.nan)

In [21]:
bundesliga.isna().sum()

Spieler                 0
Alter                   0
Nationalität            0
Position                0
Marktwert              19
Abgebender Verein       0
Aufnehmender Verein     0
Ablöse                 66
dtype: int64

In [22]:
import numpy as np

premier_league["Ablöse"] = premier_league["Ablöse"].replace({
    "ablösefrei": "0",
    "?": np.nan,
    "-": np.nan
})

premier_league["Marktwert"] = premier_league["Marktwert"].replace("-", np.nan)

In [23]:
premier_league.isna().sum()

Spieler                 0
Alter                   0
Nationalität            0
Position                0
Marktwert               6
Abgebender Verein       0
Aufnehmender Verein     0
Ablöse                 35
dtype: int64

## 3. Export für Power BI

Der bereinigte Datensatz wird als CSV-Datei exportiert und anschließend
in Power BI für die Analyse und Visualisierung verwendet.

In [24]:
bundesliga.to_csv("transfermarkt_bundesliga_bereinigt.csv", index=False, sep=";")

In [25]:
premier_league.to_csv("transfermarkt_premier_league_bereinigt.csv", index=False, sep=";")